---
functional:
  - Пользователь должен иметь возможность регистрации на сайте.
  - Пользователь должен иметь возможность авторизации на сайте.
  - Пользователь должен иметь возможность просмотра архивных баттлов.
  - Пользователь должен иметь возможность просмотра текущего баттла наблюдателем в режиме online.
  - Пользователь должен иметь возможность выбора языка программирования в терминале баттла.
  - Пользователь должен иметь возможность выбора в терминале баттла локации странички (русский и английский).
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя от изменений.
  - Сайт должен быть удобным на мобильном устройстве?.
  - Сайт должен быть совместим с последними версиями браузеров Google Chrome, Firefox, Microsoft Edge, Safari.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей.
implicit:
  - Участники не могут писать и изменять код соперника.
  - Зрители не могут писать код и вносить изменения в код участников.
