---
functional:
  - Пользователь должен иметь возможность авторизации на сайте.
  - Пользователь должен иметь возможность авторизации через Github.
  - Пользователь должен иметь возможность просмотра истории баттлов.
  - Пользователь должен иметь возможность просмотра повтора баттла.
  - Пользователь должен иметь возможность просмотра баттла зрителем в режиме online.
  - Пользователь должен иметь возможность выбора языка программирования в терминале баттла.
  - Пользователь должен иметь возможность менять выриант языка сайта (русский и английский).
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Участники не могут писать и изменять код соперника.
  - Зрители не могут писать код и вносить изменения в код участников.
